USE [master]
GO

/****** Object:  Database [SystemShop]    Script Date: 06.04.2024 9:07:58 ******/
DROP DATABASE [SystemShop]
GO

/****** Object:  Database [SystemShop]    Script Date: 06.04.2024 9:07:58 ******/
CREATE DATABASE [SystemShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SystemShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SystemShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SystemShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SystemShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SystemShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SystemShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SystemShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SystemShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SystemShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SystemShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [SystemShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SystemShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SystemShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SystemShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SystemShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SystemShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SystemShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SystemShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SystemShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SystemShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SystemShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SystemShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SystemShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SystemShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SystemShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SystemShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SystemShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SystemShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SystemShop] SET  MULTI_USER 
GO

ALTER DATABASE [SystemShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SystemShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SystemShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SystemShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SystemShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SystemShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SystemShop] SET QUERY_STORE = ON
GO

ALTER DATABASE [SystemShop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SystemShop] SET  READ_WRITE 
GO


